const FETCH_INTERVALS_BY_DAY_START: string = 'FETCH_INTERVALS_BY_DAY_START';
const FETCH_INTERVALS_BY_DAY_SUCCESS: string = 'FETCH_INTERVALS_BY_DAY_SUCCESS';
const FETCH_INTERVALS_BY_DAY_FAILURE: string = 'FETCH_INTERVALS_BY_DAY_FAILURE';

export {
  FETCH_INTERVALS_BY_DAY_START,
  FETCH_INTERVALS_BY_DAY_SUCCESS,
  FETCH_INTERVALS_BY_DAY_FAILURE
};
