const FETCH_INTERVALS_BY_DAY_START = 'FETCH_INTERVALS_BY_DAY_START';
const FETCH_INTERVALS_BY_DAY_SUCCESS = 'FETCH_INTERVALS_BY_DAY_SUCCESS';
const FETCH_INTERVALS_BY_DAY_FAILURE = 'FETCH_INTERVALS_BY_DAY_FAILURE';

export {
  FETCH_INTERVALS_BY_DAY_START,
  FETCH_INTERVALS_BY_DAY_SUCCESS,
  FETCH_INTERVALS_BY_DAY_FAILURE
};
