const FETCH_STATS_START = 'FETCH_STATS_START';
const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
const FETCH_STATS_FAILURE = 'FETCH_STATS_FAILURE';

const INC_INTERVALS = 'INC_INTERVALS';
const INC_INTERVALS_FAILURE = 'INC_INTERVALS_FAILURE';

export {
  FETCH_STATS_START,
  FETCH_STATS_SUCCESS,
  FETCH_STATS_FAILURE,
  INC_INTERVALS,
  INC_INTERVALS_FAILURE
};
