(window.webpackJsonp=window.webpackJsonp||[]).push([[1],{67:function(e,t,a){"use strict";a.r(t);var s=a(0),n=a.n(s),c=a(9),r=a(2);const l=r.c.main.withConfig({displayName:"StatsWrapper",componentId:"sc-17i8t3x"})`
  display: grid;
  justify-content: center;
`;var i=a(4),o=a(25),u=a(6),b=a(33);const d=({stats:e})=>e,m=Object(u.a)([d],({statsByDay:e})=>e);Object(u.a)([d],({isFetching:e})=>e),Object(u.a)([d],({error:e})=>e);var p=a(66),j=a.n(p),v=a(1);const O=r.c.div.withConfig({displayName:"StatsChartWrapper",componentId:"sc-iczysd"})`
  position: relative;
  width: 90vw;
  max-width: 700px;
  height: 100%;
  margin: 20px;
`;var g=({statsValues:e,dates:t,suggestedMax:a=20,label:c="",stepSize:r=1})=>{const l=Object(s.useRef)(null),i=Object(s.useRef)();return Object(s.useEffect)(()=>(l.current&&(l.current.getContext("2d"),i.current=new j.a(l.current,{type:"bar",data:{labels:t,datasets:[{label:c,backgroundColor:t.map((e,t)=>t%2==0?v.b:v.c),borderColor:"rgb(255, 99, 132)",data:e}]},options:{responsiveAnimationDuration:0,legend:{fullWidth:!0,align:"center"},hover:{animationDuration:0},responsive:!0,maintainAspectRatio:!0,scales:{yAxes:[{ticks:{beginAtZero:!0,stepSize:r,suggestedMax:a}}]}}})),()=>{i.current&&i.current.destroy()}),[l,e,t,i]),n.a.createElement(O,null,n.a.createElement("canvas",{ref:l,style:{display:"block"}}))};var y=({days:e})=>{const t=Object(i.b)(),a=Object(i.c)((e=>Object(u.a)([m],t=>{const a=Object(b.a)(e,t);return{dates:Object.keys(a),values:Object.values(a).map(e=>e?Math.floor(e.time/60):0)}}))(e)),r=Object(i.c)((e=>Object(u.a)([m],t=>{const a=Object(b.a)(e,t),s=Object.values(a).map(e=>e?Object.values(e.tasks).reduce((e,t)=>e+=t,0):0);return{dates:Object.keys(a),values:s}}))(e)),l=Object(i.c)(m);Object(s.useEffect)(()=>{l||t(Object(o.b)())},[l]);const d=Object(s.useMemo)(()=>r,[l,r]),p=Object(s.useMemo)(()=>a,[l,a]);return n.a.createElement(n.a.Fragment,null,n.a.createElement(c.a,{level:"h2",mtop:28},"intervals"),n.a.createElement(g,{dates:d.dates,statsValues:d.values,label:"intervals",suggestedMax:15}),n.a.createElement(c.a,{level:"h2",mtop:28},"time"),n.a.createElement(g,{dates:p.dates,label:"minutes",statsValues:p.values,suggestedMax:200,stepSize:20}))},h=a(29),f=a(44);t.default=()=>{const e=["last 7 days","last 14 days","last 30 days"],[t,a]=Object(s.useState)(e[0]);return n.a.createElement(l,null,n.a.createElement(c.a,{level:"h1"},"stats"),n.a.createElement(f.a,{selected:t,selectors:e,onChange:e=>a(e.currentTarget.value)}),n.a.createElement(y,{days:parseInt(t.split(" ")[1])}),n.a.createElement(h.a,null,"back"))}}}]);