const START_TIMER = 'START_TIMER';
const PAUSE_TIMER = 'PAUSE_TIMER';
const RESET_TIMER = 'RESET_TIMER';
const SHOW_MENU = 'SHOW_MENU';
const SET_TIMERS_DURATION_START = 'SET_TIMERS_DURATION_START';
const SET_TIMERS_DURATION_SUCCES = 'SET_TIMERS_DURATION_SUCCES';
const SET_TIMERS_DURATION_FAILURE = 'SET_TIMERS_DURATION_FAILURE';
const SKIP_BREAK = 'SKIP_BREAK';
const STOP_AND_SWITCH_FAZE = 'STOP_AND_SWITCH_FAZE';
const FETCH_CONFIG_START = 'FETCH_CONFIG_START';
const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
const FETCH_CONFIG_FAILURE = 'FETCH_CONFIG_FAILURE';

export {
  START_TIMER,
  PAUSE_TIMER,
  RESET_TIMER,
  SKIP_BREAK,
  STOP_AND_SWITCH_FAZE,
  SHOW_MENU,
  SET_TIMERS_DURATION_START,
  SET_TIMERS_DURATION_SUCCES,
  SET_TIMERS_DURATION_FAILURE,
  FETCH_CONFIG_START,
  FETCH_CONFIG_SUCCESS,
  FETCH_CONFIG_FAILURE
};
