const UPDATE_TIMER: string = 'UPDATE_TIMER';
const START_PAUSE_TIMER: string = 'START_PAUSE_TIMER';
const RESET_RETRY_TIMER: string = 'RESET_RETRY_TIMER';
const SWITCH_FAZE: string = 'SWITCH_FAZE';
const CREATE_CATEGORY: string = 'CREATE_CATEGORY';
const DELETE_CATEGORY: string = 'DELETE_CATEGORY';
const SWITCH_CATEGORY: string = 'SWITCH_CATEGORY';
const SHOW_MENU: string = 'SHOW_MENU';
const SET_TIMERS: string = 'SET_TIMERS';

export {
  UPDATE_TIMER,
  START_PAUSE_TIMER,
  RESET_RETRY_TIMER,
  SWITCH_FAZE,
  CREATE_CATEGORY,
  DELETE_CATEGORY,
  SWITCH_CATEGORY,
  SHOW_MENU,
  SET_TIMERS
};
