const START_TIMER: string = 'START_TIMER';
const PAUSE_TIMER: string = 'PAUSE_TIMER';
const RESET_TIMER: string = 'RESET_TIMER';
const SHOW_MENU: string = 'SHOW_MENU';
const SET_TIMERS_START: string = 'SET_TIMERS_START';
const SET_TIMERS_SUCCES: string = 'SET_TIMERS_SUCCES';
const SET_TIMERS_FAILURE: string = 'SET_TIMERS_FAILURE';
const SKIP_BREAK = 'SKIP_BREAK';
const STOP_AND_SWITCH_FAZE: string = 'STOP_AND_SWITCH_FAZE';
const FETCH_INITIAL_STATE_START: string = 'FETCH_INITIAL_STATE_START';
const FETCH_INITIAL_STATE_SUCCES: string = 'FETCH_INITIAL_STATE_SUCCES';
const FETCH_INITIAL_STATE_FAILURE: string = 'FETCH_INITIAL_STATE_FAILURE';

export {
  START_TIMER,
  PAUSE_TIMER,
  RESET_TIMER,
  SKIP_BREAK,
  STOP_AND_SWITCH_FAZE,
  SHOW_MENU,
  SET_TIMERS_START,
  SET_TIMERS_SUCCES,
  SET_TIMERS_FAILURE,
  FETCH_INITIAL_STATE_START,
  FETCH_INITIAL_STATE_SUCCES,
  FETCH_INITIAL_STATE_FAILURE
};
