const SHOW_MENU = 'SHOW_MENU';
const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

export {
  SHOW_MENU,
  CREATE_NOTIFICATION,
  HIDE_NOTIFICATION,
  CLEAR_NOTIFICATION,
};
