const GET_USER: string = 'GET_USER';
const GET_CURRENT_USER_START: string = 'GET_CURRENT_USER_START';
const GET_CURRENT_USER_SUCCES: string = 'GET_CURRENT_USER_SUCCES';
const GET_CURRENT_USER_FAILURE: string = 'GET_CURRENT_USER_FAILURE';

const LOGIN_START: string = 'LOGIN_START';
const LOGIN_SUCCESS: string = 'LOGIN_SUCCESS';
const LOGIN_FAILURE: string = 'LOGIN_FAILURE';
const REGISTER_START: string = 'REGISTER_START';
const REGISTER_SUCCESS: string = 'REGISTER_SUCCESS';
const REGISTER_FAILURE: string = 'REGISTER_FAILURE';

const SIGN_OUT_START: string = 'SIGN_OUT_START';
const SIGN_OUT_SUCCESS: string = 'SIGN_OUT_SUCCESS';
const SIGN_OUT_FAILURE: string = 'SIGN_OUT_FAILURE';

export {
  GET_USER,
  GET_CURRENT_USER_START,
  GET_CURRENT_USER_SUCCES,
  GET_CURRENT_USER_FAILURE,
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  REGISTER_START,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  SIGN_OUT_START,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_FAILURE
};
