const GET_USER: string = 'GET_USER';
const GET_CURRENT_USER_START: string = 'GET_CURRENT_USER_START';
const GET_CURRENT_USER_SUCCES: string = 'GET_CURRENT_USER_SUCCES';
const GET_CURRENT_USER_FAILURE: string = 'GET_CURRENT_USER_FAILURE';
export {
  GET_USER,
  GET_CURRENT_USER_START,
  GET_CURRENT_USER_SUCCES,
  GET_CURRENT_USER_FAILURE
};
