const CREATE_TASK: string = 'CREATE_TASK';
const EDIT_TASK: string = 'EDIT_TASK';
const DELETE_TASK: string = 'DELETE_TASK';
const SWITCH_TASK: string = 'SWITCH_TASK';
const UPDATE_TIMER: string = 'UPDATE_TIMER';
const START_TIMER: string = 'START_TIMER';
const PAUSE_TIMER: string = 'PAUSE_TIMER';
const RESET_TIMER: string = 'RESET_TIMER';
const SWITCH_FAZE: string = 'SWITCH_FAZE';
const SHOW_MENU: string = 'SHOW_MENU';
const SET_TIMERS: string = 'SET_TIMERS';
const GET_USER: string = 'GET_USER';
const REGISTER: string = 'REGISTER';
const STOP_AND_SWITCH_FAZE: string = 'STOP_AND_SWITCH_FAZE';

export {
  CREATE_TASK,
  EDIT_TASK,
  DELETE_TASK,
  SWITCH_TASK,
  UPDATE_TIMER,
  START_TIMER,
  PAUSE_TIMER,
  RESET_TIMER,
  STOP_AND_SWITCH_FAZE,
  SWITCH_FAZE,
  SHOW_MENU,
  SET_TIMERS,
  GET_USER,
  REGISTER
};
