const CREATE_TASK: string = 'CREATE_TASK';
const EDIT_TASK: string = 'EDIT_TASK';
const DELETE_TASK: string = 'DELETE_TASK';
const SWITCH_TASK: string = 'SWITCH_TASK';
const UPDATE_TIMER: string = 'UPDATE_TIMER';
const START_TIMER: string = 'START_TIMER';
const PAUSE_TIMER: string = 'PAUSE_TIMER';
const RESET_TIMER: string = 'RESET_TIMER';
const SHOW_MENU: string = 'SHOW_MENU';
const SET_TIMERS: string = 'SET_TIMERS';
const SKIP_BREAK = 'SKIP_BREAK';
const GET_USER: string = 'GET_USER';
const STOP_AND_SWITCH_FAZE: string = 'STOP_AND_SWITCH_FAZE';
const GET_INITIAL_STATE: string = 'GET_INITIAL_STATE';
const FETCH_INITIAL_STATE_START: string = 'FETCH_INITIAL_STATE_START';
const FETCH_INITIAL_STATE_SUCCES: string = 'FETCH_INITIAL_STATE_SUCCES';
const FETCH_INITIAL_STATE_FAILURE: string = 'FETCH_INITIAL_STATE_FAILURE';
const GET_CURRENT_USER_START: string = 'GET_CURRENT_USER_START';
const GET_CURRENT_USER_SUCCES: string = 'GET_CURRENT_USER_SUCCES';
const GET_CURRENT_USER_FAILURE: string = 'GET_CURRENT_USER_FAILURE';
export {
  CREATE_TASK,
  EDIT_TASK,
  DELETE_TASK,
  SWITCH_TASK,
  UPDATE_TIMER,
  START_TIMER,
  PAUSE_TIMER,
  RESET_TIMER,
  SKIP_BREAK,
  STOP_AND_SWITCH_FAZE,
  SHOW_MENU,
  SET_TIMERS,
  GET_USER,
  GET_INITIAL_STATE,
  FETCH_INITIAL_STATE_START,
  FETCH_INITIAL_STATE_SUCCES,
  FETCH_INITIAL_STATE_FAILURE,
  GET_CURRENT_USER_START,
  GET_CURRENT_USER_SUCCES,
  GET_CURRENT_USER_FAILURE
};
