const UPDATE_TIMER: string = 'UPDATE_TIMER';
const START_PAUSE_TIMER: string = 'START_PAUSE_TIMER';
const RESET_RETRY_TIMER: string = 'RESET_RETRY_TIMER';
const SWITCH_FAZE: string = 'SWITCH_FAZE';

export { UPDATE_TIMER, START_PAUSE_TIMER, RESET_RETRY_TIMER, SWITCH_FAZE };
