const SET_TIMER: string = 'SET_TIMER';
const START_PAUSE_TIMER: string = 'START_PAUSE_TIMER';
const RESET_TIMER: string = 'RESET_TIMER';
const RETRY_TIMER: string = 'RETRY_TIMER';

export { SET_TIMER, START_PAUSE_TIMER, RESET_TIMER, RETRY_TIMER };
