const CREATE_TASK_START = 'CREATE_TASK_START';
const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

const EDIT_TASK_START = 'EDIT_TASK_START';
const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE';

const DELETE_TASK_START = 'DELETE_TASK_START';
const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

const SWITCH_TASK = 'SWITCH_TASK';

const SWITCH_TASK_START = 'SWITCH_TASK_START';
const SWITCH_TASK_SUCCESS = 'SWITCH_TASK_SUCCESS';
const SWITCH_TASK_FAILURE = 'SWITCH_TASK_FAILURE';

export {
  CREATE_TASK_START,
  CREATE_TASK_SUCCESS,
  CREATE_TASK_FAILURE,
  EDIT_TASK_START,
  EDIT_TASK_SUCCESS,
  EDIT_TASK_FAILURE,
  DELETE_TASK_START,
  DELETE_TASK_SUCCESS,
  DELETE_TASK_FAILURE,
  SWITCH_TASK_START,
  SWITCH_TASK_SUCCESS,
  SWITCH_TASK_FAILURE
};
