const CREATE_TASK_START: string = 'CREATE_TASK_START';
const CREATE_TASK_SUCCESS: string = 'CREATE_TASK_SUCCESS';
const CREATE_TASK_FAILURE: string = 'CREATE_TASK_FAILURE';
const EDIT_TASK: string = 'EDIT_TASK';
const DELETE_TASK: string = 'DELETE_TASK';
const SWITCH_TASK: string = 'SWITCH_TASK';

export {
  EDIT_TASK,
  DELETE_TASK,
  SWITCH_TASK,
  CREATE_TASK_START,
  CREATE_TASK_SUCCESS,
  CREATE_TASK_FAILURE
};
